# Pipeline solo para Glue Jobs creados desde un Script Editor
name: glue-jobs-deploy 
run-name: Glue Jobs Deployment Pipeline

on:  
  push:
    branches: 
      - developer
    paths:
      - "**.json"
      
  workflow_dispatch:
  
env:
   S3_ROUTE: ""
   FILENAME: "./sales-not-null/sales-not-null.json"

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: Download Source Code
        uses: actions/checkout@v4
        with:
          ref: developer
      - name: Extract S3 Bucket Name   
        run: |
              pwd
              ls -la
              S3_ROUTE=$(grep 'scriptLocation' $FILENAME | awk -F ': ' '{gsub(/"|,/, "", $2); print $2}')
              echo "Ubicacion del script: $S3_ROUTE"    
