# Pipeline solo para Glue Jobs creados desde un Script Editor
name: glue-jobs-deploy 

on:
  push:
    branches: 
            - developer
    paths:
      - "**.json"
env:
   SCRIPT_LOCATION = ""
   FILE_PATH="/sales-not-null/sales-not-null.json"

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: Download source code
        uses: actions/checkout@v2

  #    - name: Extract bucket name 
  #      run: |
  #      SCRIPT_LOCATION=$(grep 'scriptLocation' $FILENAME | awk -F ': ' '{gsub(/"|,/, "", $2); print $2}')
  #      echo "Ubicacion del script: $SCRIPT_LOCATION"  

  # deploy:
  #   needs: checkout
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download script
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: job.py
          
      # - name: Download and install AWS CLI
      #   if: success()
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install

      # - name: Configure AWS credentials
      #   if: success()
      #   shell: bash
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #   run: |
      #     mkdir -p ~/.aws
      #     touch ~/.aws/credentials
      #     echo "[default]
      #     aws_access_key_id = $AWS_ACCESS_KEY
      #     aws_secret_access_key = $AWS_SECRET_KEY" > ~/.aws/credentials
          
      # - name: Upload script to S3
      #   if: success()
      #   run: aws s3 cp job.py s3://${{secrets.S3_BUCKET_NAME}}/job_${GITHUB_SHA}.py --region us-east-1
      
      # - name: Deploy Script in Glue job
      #   if: success()
      #   run: |
      #     aws glue update-job --job-name "PoC Job" --job-update \
      #       "Role=AWSGlueServiceRole-PoC,Command={Name=glueetl,ScriptLocation=s3://${{secrets.S3_BUCKET_NAME}}/job_${GITHUB_SHA}.py},Connections={Connections=redshift}" \
      #       --region us-east-1
      
      # - name: Remove AWS credentials
      #   run: rm -rf ~/.aws
