# Pipeline solo para Glue Jobs creados desde un Script Editor
name: glue-jobs-deploy 
run-name: Glue Jobs Deployment Pipeline

on:  
  push:
    branches: 
      - main
    paths:
      - "**.json"
      
  workflow_dispatch:
  
env:
   S3_ROUTE: ""
   FILENAME: "./sales-not-null/sales-not-null.json"
   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
   AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps: 
      - name: Download Source Code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Extract S3 Bucket Name   
        run: |
              S3_ROUTE = $(grep 'scriptLocation' $FILENAME | awk -F ': ' '{gsub(/"|,/, "", $2); print $2}')
              echo "S3_ROUTE=$S3_ROUTE" >> $GITHUB_ENV
  deploy:
    needs: checkout
    runs-on: ubuntu-latest
    steps:  
    
       - name: print variable
         run: echo '$S3_ROUTE'
         
       - name: Download script to S3
         uses: keithweaver/aws-s3-github-action@v1.0.0
         with:
           command: cp
           source: $S3_ROUTE
           aws_access_key_id: $AWS_ACCESS_KEY
           aws_secret_access_key: $AWS_SECRET_KEY
           aws_region: us-east-1
